Disable Swift compiler sandboxing in Xcode 15.3+ to fix nested sandboxing
bazelbuild/rules_swift pull request #1206
Opened 2024-05-22 03:10 UTC by adincebic

This should solve https://github.com/bazelbuild/rules_swift/issues/1202
 and #1204

> There were issues with Swift compiler plugins (incl. macros) and nested sandboxes on macOS with Swift 5.9 that have been fixed with 5.10:
> swift: [apple/swift#70079](https://github.com/apple/swift/pull/70079)
> swift-driver: [apple/swift-driver#1493](https://github.com/apple/swift-driver/pull/1493)
> swift-package-manager: [apple/swift-package-manager#7167](https://github.com/apple/swift-package-manager/pull/7167)

I am not sure whether this flag is required on Linux too.

2024-05-22 03:36 UTC, luispadron commented on swift/internal/xcode_swift_toolchain.bzl
> +        swiftcopts.append("-disable-sandbox")
Should this only be added to the `swift_compiler_plugin`?

2024-05-22 04:01 UTC, luispadron approved these changes

2024-05-22 04:03 UTC, luispadron commented on swift/internal/xcode_swift_toolchain.bzl
> +    # We pass '-disable-sandbox' to allow compiling targets with Swift compiler plugins in Bazel sandbox on Xcode 15.3+
Maybe some more info on the issue it causes / links to the swift issues, from JP:

> There were issues with Swift compiler plugins (incl. macros) and nested sandboxes on macOS with Swift 5.9 that have been fixed with 5.10:
> swift: https://github.com/apple/swift/pull/70079
> swift-driver: https://github.com/apple/swift-driver/pull/1493
> swift-package-manager: https://github.com/apple/swift-package-manager/pull/7167

2024-05-22 12:01 UTC, brentleyjones requested changes

2024-05-22 12:01 UTC, brentleyjones commented on swift/internal/xcode_swift_toolchain.bzl
> +        swiftcopts.append("-disable-sandbox")
I think instead of setting the foot directly here, we should instead implicitly enable a feature that sets it (there should be other examples of that in the toolchain as well). That way people can opt out of it if they want for some reason. Then we can use a configurator to add the flag in the right order (right now this is being applied after user defined swiftcopts, which is wrong).

2024-05-22 14:47 UTC, luispadron commented
Is it possible to add a test case as well for this, would catch regressions in the future

2024-05-22 16:03 UTC, brentleyjones requested changes

2024-05-22 16:03 UTC, brentleyjones commented on swift/internal/feature_names.bzl
> +# If enabled '#Preview' macro provided by SwiftUI fails to build and probably other system-provided macros.
```suggestion
# Disables Swift sandbox which prevents issues with nested sandboxing when Swift code contains system-provided macros.
# If enabled '#Preview' macro provided by SwiftUI fails to build and probably other system-provided macros.
# Enabled by default for Swift 5.10+ on macOS.
```

2024-05-22 16:03 UTC, brentleyjones commented on swift/internal/feature_names.bzl
> +SWIFT_FEATURE__DISABLE_SWIFT_SANDBOX = "swift._disable_swift_sandbox"
```suggestion
SWIFT_FEATURE_DISABLE_SWIFT_SANDBOX = "swift.disable_swift_sandbox"
```

2024-05-22 16:03 UTC, brentleyjones commented on swift/internal/xcode_swift_toolchain.bzl
> +    "SWIFT_FEATURE__DISABLE_SWIFT_SANDBOX",
Once renamed to remove the `_`, please move it up.

2024-05-22 16:03 UTC, brentleyjones commented on swift/internal/xcode_swift_toolchain.bzl
> +        requested_features.append(SWIFT_FEATURE__DISABLE_SWIFT_SANDBOX)
Yes. They would do `--features=-swift.disable_swift_sandbox`.

2024-05-22 18:27 UTC, luispadron approved these changes
Thanks for fixing up and addressing comments!

2024-05-22 20:08 UTC, keith commented
Is this fixed in 15.4?

2024-05-22 21:11 UTC, luispadron commented
@keith tested in the reproducer @adincebic provided but looks like its still broken unless we disable_sandbox:


```
<unknown>:0: warning: compiler plugin not loaded: '/Applications/Xcode-15.4.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server; failed to initialize
app/source/ContentView.swift:15:1: error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'
#Preview {
^
SwiftUI.Preview:2:41: note: 'Preview(_:body:)' declared here
@freestanding(declaration) public macro Preview(_ name: String? = nil, body: @escaping @MainActor () -> any View) = #externalMacro(module: "PreviewsMacros", type: "SwiftUIView")
    
```

2024-05-22 22:06 UTC, brentleyjones approved these changes

2024-05-22 22:13 UTC, merged

2024-06-27 02:16 UTC, PhilCai1993 commented
We use -load-plugin-library instead of executable, it works well, without the sandboxing issue