Add the ability to dump ast to a file
bazelbuild/rules_swift pull request #623
Opened 2021-05-28 03:56 UTC by segiddins

Some tooling (namely https://github.com/square/Cleanse/tree/master/cleansec) operates over dumped swift AST files.
In order to dump AST files, (almost) complete `swiftc` invocations are required, in addition to the `-dump-ast` flag.
Because almost the same set of arguments as module compilation are used for dumping the AST, it is nearly impossible for a bazel user to reconstruct them by hand (or via a standalone rule).

This new output group (and action) serves to dump AST files for each swift source file in a `swift_library` swift module.

2021-05-28 04:43 UTC, thii approved these changes

2021-05-28 12:44 UTC, brentleyjones commented on swift/internal/derived_files.bzl
> +    """Declares a file for an intermediate object file during compilation.
The comment is incorrect (copied from `_intermediate_object_file`). Can you also be more specific in the comments for the args and returns?

2021-05-28 17:03 UTC, jerrymarino commented
I think there's more to running this frontend action in Bazel than dumping the args: it allows us to schedule the actions with Bazel. That being said, I think we could run different frontend actions with an aspect and simplify the code. What are the tradeoffs of doing that approach? 

I was also wondering about the use cases forit. I imagine that I'd want to run this frontend action seperately than a compiler invocation. For example, I'd like to extract ASTs but not run code generation for object files. If that's possible maybe we should disable object file generation.  Is that possible?

2021-05-28 17:04 UTC, jerrymarino commented
I think there's more to running this frontend action in Bazel than dumping the args: it allows us to schedule the actions with Bazel. That being said, I think we could run different frontend actions with an aspect and simplify the code. What are the tradeoffs of doing that approach? 

I was also wondering about the use cases of this feature. I imagine that I'd want to run this frontend action separately than an code emitting compiler invocation. For example, I'd like to extract ASTs but not run code generation for object files. If that's possible maybe we should disable object file generation.  Is that possible?

2021-05-28 17:21 UTC, segiddins commented
> Doesn't bazel aquery provide this?

Yes, but not in a way that can easily be integrated into a rule (and we'd like to consume the dumped AST in rules!)

2021-05-28 17:26 UTC, segiddins commented
>  I imagine that I'd want to run this frontend action separately than an code emitting compiler invocation. For example, I'd like to extract ASTs but not run code generation for object files. If that's possible maybe we should disable object file generation. Is that possible?

That's what's happening here, since dumping the AST is generated from a separate action.

> That being said, I think we could run different frontend actions with an aspect and simplify the code.

That would almost certainly be _more_ code, since rules_swift exposes no way to get at the configurators used to construct the `swiftc` invocations, and `-dump-ast` uses a subset of the flags used for `-emit-object` or `-emit-swiftmodule`

2021-05-28 18:57 UTC, jerrymarino commented
>That's what's happening here, since dumping the AST is generated from a separate action.

Ah so I can specify the output group then and just run the AST actions? That's pretty cool.


> That would almost certainly be more code

It could be nice if that approach can simplifies the core of `rules_swift`: less features, less outputs, and less logic on the compilation side of things, and maybe different code this feature.

FWIW I've seen some code use an aspect to setup a compdb as well strictly based on args and metadata from rules. I'll try to dig that up to get a reference to it to see if it's applicable or helpful to consider if it's viable

2021-05-28 20:24 UTC, jerrymarino commented
PS: the aspect was something like this
```py
# print args
def _a_impl(target, ctx):
  for action in target.actions:
    if action.mnemonic == "SwiftCompile":
      action_args = action.argv
      print("ARGS", action_args)
      # TODO: schedule action here
  return []

print_aspect = aspect(
  implementation = _a_impl,
  attr_aspects = ['deps'],
)```

2021-05-28 23:21 UTC, keith approved these changes

2021-05-28 23:21 UTC, keith commented on swift/internal/compiling.bzl
> +                swift_toolchain_config.add_arg("-suppress-warnings"),
not sure about this one, seems like something you should probably pass manually as needed?

2021-05-28 23:21 UTC, keith commented on tools/worker/swift_runner.cc
> +        // we didn't know at analysis time.
looks like you can revert this file

2021-05-28 23:22 UTC, segiddins commented on swift/internal/compiling.bzl
> +                swift_toolchain_config.add_arg("-suppress-warnings"),
probably -- i guess it just means duplicated warnings for the same file/line ?

2021-05-28 23:26 UTC, keith commented on swift/internal/compiling.bzl
> +                swift_toolchain_config.add_arg("-suppress-warnings"),
Ohh, in the case you're building both at once? interesting yea, seems fine to leave

2021-05-29 01:20 UTC, jerrymarino approved these changes

2021-06-08 18:11 UTC, jerrymarino commented on tools/worker/swift_runner.cc
> +        // we didn't know at analysis time.
I hit the same issue on my PR and it is due to the master branch not having clang-format up to date on the files. Maybe worth just running clang-format on the repo first and rebasing to get the white space out of PRs when people run it.

2021-06-08 18:19 UTC, jerrymarino requested changes

2021-06-08 18:19 UTC, jerrymarino commented on tools/worker/work_processor.cc
> +    } else if (arg == "-dump-ast") {
@segiddins it looks like this doesn't work with the `local` strategy - can you confirm?

 I've refactored some of the argument parsing logic in [this PR](https://github.com/bazelbuild/rules_swift/pull/567) so is now possible to strip off arguments and parse arguments to ivars in the runner.

2021-06-14 17:29 UTC, segiddins commented on tools/worker/work_processor.cc
> +    } else if (arg == "-dump-ast") {
👍🏻  now handled in both places (runner for avoiding setting WMO flag, work processor for avoiding incremental mode as well)

2021-06-14 20:00 UTC, keith approved these changes

2021-06-15 19:57 UTC, brentleyjones approved these changes

2021-06-15 19:57 UTC, brentleyjones commented on swift/internal/compiling.bzl
> +        ast_files = compile_outputs.ast_files,
nit: can this be at the top to preserve ordering?

2021-06-15 19:57 UTC, brentleyjones commented on swift/internal/compiling.bzl
> +    ast_files = []
Should this have a comment like the other ones?

2021-06-15 19:57 UTC, brentleyjones commented on swift/internal/compiling.bzl
> +        ast_files = ast_files,
nit: can this be moved to the top?

2021-06-15 19:57 UTC, brentleyjones commented on swift/internal/compiling.bzl
> +
nit: Can this be moved to above `if compilation_outputs.indexstore` to keep it alphabetical?

2021-06-15 20:03 UTC, merged